<?php

namespace AppBundle\Repository;

/**
 * KonzesioaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KonzesioaRepository extends \Doctrine\ORM\EntityRepository
{
}
