<?php

namespace AppBundle\Repository;

/**
 * SubentzioaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubentzioaRepository extends \Doctrine\ORM\EntityRepository
{
}
